version: "3"

services:
  mongo:
    image: mongo
    container_name: "<%= project.identifiers.kebab %>-mongo"
    ports:
      - "27017:27017"

  mongo_admin:
    image: mongo-express
    container_name: "<%= project.identifiers.kebab %>-mongo-express"
    links:
      - mongo
    ports:
      - "8081:8081"

  express:
    build: "./"
    container_name: "<%= project.identifiers.kebab %>-web-api"
    ports:
      - "4000:4000"
    links:
      - mongo
    depends_on:
      - mongo
